# Generated by Django 4.0.4 on 2022-04-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Pista')),
                ('difficulty', models.FloatField(blank=True, null=True, verbose_name='Dificultad')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitud')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitud')),
                ('short_description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripción breve')),
                ('full_description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripción breve')),
            ],
            options={
                'verbose_name': 'pista',
                'verbose_name_plural': 'pistas',
                'ordering': ['name'],
            },
        ),
    ]
