# Generated by Django 4.0.4 on 2022-04-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='autonomous_community',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Comunidad Autonoma'),
        ),
        migrations.AddField(
            model_name='track',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='track',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='track',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia'),
        ),
    ]
