# Generated by Django 4.0.4 on 2022-04-17 14:51

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_track_autonomous_community_track_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Título')),
                ('image_imageTrack', models.ImageField(upload_to=home.models.upload_to)),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='track_image', to='home.track')),
            ],
            options={
                'verbose_name': 'Imagen pista',
                'verbose_name_plural': 'Imagen de pistas',
                'ordering': ['name'],
            },
        ),
    ]
